### ISSUE TITLE
How to read data via USB-serial port?

### ISSUE THREAD

**Issue by imarin18** [labstreaminglayer/App-SerialPort#2]
Dear Sir or Madam,

I would like to read the data from an external device via a USB-serial communication. I found the following page but could not debug the C++ code properly.
https://github.com/labstreaminglayer/App-SerialPort

Could you please check whether the programme works properly?

Thank you very much for the guidance you could provide.

Best regards,
imarin18

**Comment by tstenner** [comment]
The app hasn't been touched in quite some time, but from what I can see it should still do its job.
The serial port type (native, USB, emulated) shouldn't make any difference, you just need to find out the port settings (most importantly, the COM port index).

For testing, I suggest [PuTTY](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html) ([documentation](https://the.earth.li/~sgtatham/putty/0.74/htmldoc/Chapter3.html#using-serial)).
Once you've found settings that work for your device, you can use the same settings in this app.

**Comment by imarin18** [comment]
Thank you very much for your reply and the guidance.
Ok I will try to run the scripts.
